

package com.soarex.autofactory.kotlin.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.soarex.autofactory.kotlin.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
    @Test
    public void testAllFilesPresentInBox() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("companionGeneration.kt")
    public void testCompanionGeneration() throws Exception {
        runTest("testData/box/companionGeneration.kt");
    }

    @Test
    @TestMetadata("companionMembersGeneration.kt")
    public void testCompanionMembersGeneration() throws Exception {
        runTest("testData/box/companionMembersGeneration.kt");
    }

    @Test
    @TestMetadata("constructorTransformer.kt")
    public void testConstructorTransformer() throws Exception {
        runTest("testData/box/constructorTransformer.kt");
    }
}
